#For this problem, you'll create a makefile like the previous ones, 
#but this one will be different in these ways:
#
#1) The header files are not in the same directory as the sources. 
#   Thus, you won't be able to do this:
#   Dog.o: Dog.h 
#   because make will look for Dog.h in the sources directory.  
#   See the lab assignment page for more details.
#
#   You also will need to tell the g++ compiler where the header files
#   are.  See the lab assignment page for more details.
#
#2) The executable produced needs to be moved into the bin directory.
#   Thus, when you execute it, you need to account for it not being
#   in this directory. You will also need to explicitly provide
#   the link step before the move command. (If you provide any commands 
#   after a 
#   target: dependences 
#   line then make won't performed any implied commands.)
#
#Note: Be sure to provide all of the same kinds of macros and targets
#      that you did in the previous two problems.
#
#Note: Don't define a macro name PATH. There is already an environment 
#      variable with that name.
#
#Note: Don't use touch with a file that doesn't exist.  For example,
#      don't type touch Dog.h from within the sources directory.
#
